// Headless smoke test of the magazine ECS in world.wasm: bun scripts/magazine/world-smoke.ts
import { wasiImports } from '../../src/lib/gpu/room/world.ts';
import fs from 'node:fs';
let memory: WebAssembly.Memory;
const bytes = fs.readFileSync(new URL('../../src/lib/gpu/room/world.wasm', import.meta.url));
const { instance } = await WebAssembly.instantiate(bytes, wasiImports(() => memory) as any);
const x: any = instance.exports; memory = x.memory;
const items = [{slug:'ifd',date:'2025-01-01',archived:false,tex:[0,0,1,1]}];
const input = new TextEncoder().encode(JSON.stringify({items, signs:[[0,0,1,1],[0,0,1,1],[0,0,1,1]], map:[0,0,1,1]}));
new Uint8Array(memory.buffer, x.world_input(input.length), input.length).set(input);
console.log('build', x.world_build());
const st = () => Array.from(new Float32Array(memory.buffer, x.magazine_state_ptr(), 16)).map(v=>+v.toFixed(3));
const ev = () => { const o=[]; for(let v=x.event_poll(); v; v=x.event_poll()) o.push([v>>>24, v&0xffffff]); return o; };
const tick = (n:number, dt=16) => { for(let i=0;i<n;i++) x.world_tick(dt); };
x.spread_init(4); x.figure_define(0,0,0,12,9); x.figure_define(1,2,0,12,9); tick(1);
console.log('init', st(), ev());
const clk = () => Array.from(new Float32Array(memory.buffer, x.figure_clock_ptr(), x.figure_clock_len())).map(v=>+v.toFixed(2));
const check = (name: string, ok: boolean, extra: unknown = '') => { console.log(ok ? 'PASS' : 'FAIL', name, extra); if (!ok) process.exitCode = 1; };
tick(30); check('figures wait for settle (first paint = poster)', clk()[0] === 9 && clk()[1] === 9, clk());
x.book_settled(1); tick(30); check('hold at poster for 1 s after settle', clk()[0] === 9, clk()); tick(40); check('then plays', clk()[0] > 9, clk());
x.open_full(1); tick(10); console.log('open mid', st(), ev()); tick(60); console.log('open done', st(), ev(), clk());
x.spread_by(0); x.spread_grab(1); x.spread_by(0.5); tick(1); console.log('grab', st()); x.spread_release(0.3); tick(80); console.log('released', st(), ev());
x.spread_goto(3); tick(100); console.log('goto3', st(), ev(), clk());
x.figure_focus(1); tick(1); console.log('focus', st()[10], ev());
x.figure_focus(-1); tick(1); console.log('unfocus', st()[10], ev());
x.overview_set(1); tick(60); console.log('overview', st()[9], ev()); x.overview_set(0);
x.close_full(); tick(150); console.log('closed', st(), ev());
x.corner_drag(0.5); tick(1); console.log('corner', st()[4]); x.corner_release(0); tick(60); console.log('corner0', st()[4]);
x.bounce(); tick(10); console.log('bounce', st()[11]);
console.log('--- reader');
const rst = () => Array.from(new Float32Array(memory.buffer, x.reader_state_ptr(), 12)).map(v=>+v.toFixed(3));
console.log(x.article_open(0, 2, 40, 56, 0.6, 0)); tick(20); console.log(rst());

console.log('--- figure scrubbing');
x.spread_goto(0); x.spread_init(4); x.figure_define(0,0,0,12,9); x.figure_define(1,0,2,12,3); x.book_settled(1); tick(120);
const t0 = clk()[0]; check('autoplay advances a loop figure', t0 !== 9, clk());
x.figure_scrub_begin(0); tick(1); const hd = (() => { const o: any[] = []; for (let v = x.event_poll(); v; v = x.event_poll()) o.push([v >>> 24, v & 0xffffff]); return o; })();
x.figure_scrub_by(0, -2); tick(60); const held = clk()[0]; check('held figure does not autoplay', Math.abs(held - ((t0 - 2 + 12) % 12)) < 0.05, [t0, held]);
x.figure_scrub_by(0, 1.5); tick(30); check('scrub moves t, wraps for loops', Math.abs(clk()[0] - ((held + 1.5) % 12)) < 0.05, clk());
x.figure_scrub_end(0, 2); tick(10); const m1 = clk()[0]; tick(10); check('momentum carries on after release', clk()[0] > m1 || m1 > 11, [m1, clk()[0]]);
tick(100); const rest = clk()[0]; tick(10); check('idle after release (no autoplay before ~2 s)', Math.abs(clk()[0] - rest) < 0.12, [rest, clk()[0]]);
tick(200); check('autoplay resumes after idle', Math.abs(clk()[0] - rest) > 0.5, [rest, clk()[0]]);
x.figure_scrub_begin(1); x.figure_scrub_by(1, 100); tick(1); check('scrub-mode figure clamps to its duration', clk()[1] === 12, clk());
x.figure_scrub_by(1, -100); tick(1); check('and to zero', clk()[1] === 0, clk()); x.figure_scrub_end(1, 0); tick(300); check('scrub-mode figures never autoplay', clk()[1] === 0, clk());
x.figure_hover(0); tick(1); const ev1 = (() => { const o: any[] = []; for (let v = x.event_poll(); v; v = x.event_poll()) o.push([v >>> 24, v & 0xffffff]); return o; })();
check('hover raises FigureHover(0) and fills state[15]', ev1.some((e) => e[0] === 10 && e[1] === 0) && st()[15] === 0, [ev1, st()[15]]);
x.figure_hover(-1); tick(1); check('hover clear', st()[15] === -1, st()[15]);
x.book_settled(0); tick(1); check('closing the book resets figures to poster', clk()[0] === 9 && clk()[1] === 3, clk());
