// Headless smoke test of the magazine ECS in world.wasm: bun scripts/magazine/world-smoke.ts
import { wasiImports } from '../../src/lib/gpu/room/world.ts';
import fs from 'node:fs';
let memory: WebAssembly.Memory;
const bytes = fs.readFileSync(new URL('../../src/lib/gpu/room/world.wasm', import.meta.url));
const { instance } = await WebAssembly.instantiate(bytes, wasiImports(() => memory) as any);
const x: any = instance.exports; memory = x.memory;
const items = [{slug:'ifd',date:'2025-01-01',archived:false,tex:[0,0,1,1]}];
const input = new TextEncoder().encode(JSON.stringify({items, signs:[[0,0,1,1],[0,0,1,1],[0,0,1,1]], map:[0,0,1,1]}));
new Uint8Array(memory.buffer, x.world_input(input.length), input.length).set(input);
console.log('build', x.world_build());
const st = () => Array.from(new Float32Array(memory.buffer, x.magazine_state_ptr(), 16)).map(v=>+v.toFixed(3));
const ev = () => { const o=[]; for(let v=x.event_poll(); v; v=x.event_poll()) o.push([v>>>24, v&0xffffff]); return o; };
const tick = (n:number, dt=16) => { for(let i=0;i<n;i++) x.world_tick(dt); };
x.spread_init(4); x.figure_define(0,0,0,12,9); x.figure_define(1,2,0,12,9); tick(1);
console.log('init', st(), ev());
const clk = () => Array.from(new Float32Array(memory.buffer, x.figure_clock_ptr(), 2)).map(v=>+v.toFixed(2));
tick(30); console.log('clock', clk());
x.open_full(1); tick(10); console.log('open mid', st(), ev()); tick(60); console.log('open done', st(), ev(), clk());
x.spread_by(0); x.spread_grab(1); x.spread_by(0.5); tick(1); console.log('grab', st()); x.spread_release(0.3); tick(80); console.log('released', st(), ev());
x.spread_goto(3); tick(100); console.log('goto3', st(), ev(), clk());
x.figure_focus(1); tick(1); console.log('focus', st()[10], ev());
x.figure_focus(-1); tick(1); console.log('unfocus', st()[10], ev());
x.overview_set(1); tick(60); console.log('overview', st()[9], ev()); x.overview_set(0);
x.close_full(); tick(150); console.log('closed', st(), ev());
x.corner_drag(0.5); tick(1); console.log('corner', st()[4]); x.corner_release(0); tick(60); console.log('corner0', st()[4]);
x.bounce(); tick(10); console.log('bounce', st()[11]);
console.log('--- reader');
const rst = () => Array.from(new Float32Array(memory.buffer, x.reader_state_ptr(), 12)).map(v=>+v.toFixed(3));
console.log(x.article_open(0, 2, 40, 56, 0.6, 0)); tick(20); console.log(rst());
