// GENERATED by scripts/icons/build.ts. Do not edit. The file-type icons the page pass can draw (draw shape ICON, aux = index here); the triangles
// live in src/lib/reading/icons.gen.ts from the same run, so the two cannot drift.
pub const FILE_ICONS: &[&str] = &["rust", "toml"];
